ERR WIP: try using working-directory instead of FLY_PROJECT_PATH
Error: the config for your app is missing an app name, add an app field to the fly.toml file or specify with the -a flag